# Generated by Django 5.2.8 on 2025-12-22 23:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên khóa học')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Học phí')),
                ('skills_vector', models.JSONField(default=list, verbose_name='Vector kỹ năng (AI)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('instructor_name', models.CharField(default='Chưa có giảng viên', max_length=100)),
                ('rating', models.FloatField(default=5.0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('duration', models.CharField(default='2h 30m', max_length=50)),
                ('category', models.CharField(blank=True, default='Uncategorized', max_length=100, null=True, verbose_name='Danh mục')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='courses.course', verbose_name='Khóa học tiên quyết')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': '1. Quản lý Khóa học',
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên lớp học')),
                ('start_date', models.DateField(verbose_name='Ngày khai giảng')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('max_capacity', models.IntegerField(default=30, verbose_name='Sĩ số tối đa')),
                ('schedule', models.JSONField(default=list, verbose_name='Lịch học (JSON)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course', verbose_name='Thuộc khóa học')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': '2. Quản lý Lớp học',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề phần học')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Thuộc khóa học')),
            ],
            options={
                'verbose_name': 'Phần học',
                'verbose_name_plural': 'Phần học (Modules)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài học')),
                ('duration', models.CharField(default='10:00', max_length=20, verbose_name='Thời lượng (vd: 05:30)')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Cho phép xem trước?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự bài học')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Thuộc phần học')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học (Lessons)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày vào danh sách')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseclass', verbose_name='Lớp học hồ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Danh sách chờ',
                'verbose_name_plural': '4. Hàng chờ đăng ký',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang học'), ('COMPLETED', 'Đã hoàn thành'), ('DROPPED', 'Đã hủy')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='Điểm tổng kết')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseclass', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Đăng ký',
                'verbose_name_plural': '3. Danh sách Đăng ký',
                'unique_together': {('student', 'course_class')},
            },
        ),
    ]
