# Generated by Django 5.2.8 on 2025-12-30 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Xem khóa học'), ('CLICK', 'Click vào chi tiết'), ('RATING', 'Đánh giá sao'), ('ENROLL', 'Đăng ký học')], default='VIEW', max_length=10)),
                ('rating', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tương tác người dùng',
                'verbose_name_plural': '5. Nhật ký tương tác (AI Data)',
            },
        ),
    ]
