# Generated by Django 6.0 on 2026-01-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài kiểm tra')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('time_limit', models.IntegerField(default=30, verbose_name='Thời gian làm bài (phút)')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Điểm đạt tối thiểu (%)')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Số lần làm tối đa')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Trộn câu hỏi')),
                ('shuffle_choices', models.BooleanField(default=True, verbose_name='Trộn đáp án')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='Hiển thị đáp án đúng sau khi nộp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Bài kiểm tra khóa học',
                'verbose_name_plural': 'Bài kiểm tra khóa học',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0, verbose_name='Thời gian làm (giây)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang làm'), ('SUBMITTED', 'Đã nộp'), ('TIME_UP', 'Hết giờ')], default='IN_PROGRESS', max_length=20)),
                ('score', models.FloatField(default=0, verbose_name='Điểm số')),
                ('total_points', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('question_order', models.JSONField(default=list, verbose_name='Thứ tự câu hỏi đã trộn')),
                ('choice_orders', models.JSONField(default=dict, verbose_name='Thứ tự đáp án đã trộn')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.coursequiz', verbose_name='Bài kiểm tra')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Lần làm bài',
                'verbose_name_plural': 'Lịch sử làm bài',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('explanation', models.TextField(blank=True, verbose_name='Giải thích đáp án')),
                ('points', models.IntegerField(default=1, verbose_name='Điểm số')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.coursequiz', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='Nội dung đáp án')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Đáp án đúng')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.coursequizquestion', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Đáp án',
                'verbose_name_plural': 'Đáp án',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.coursequizattempt', verbose_name='Lần làm bài')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursequizchoice', verbose_name='Đáp án đã chọn')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursequizquestion', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Câu trả lời',
                'verbose_name_plural': 'Câu trả lời',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
