# Generated by Django 5.2.8 on 2025-12-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
