# Generated by Django 6.0 on 2026-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='is_quizzed',
            field=models.BooleanField(default=False),
        ),
    ]
