# Generated by Django 5.2.8 on 2026-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_user_avatar_user_bio_user_birth_date_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link gốc khóa học'),
        ),
        migrations.AddField(
            model_name='course',
            name='imported_enrollments',
            field=models.IntegerField(default=0, verbose_name='Số lượng học viên (từ dataset)'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tổ chức cấp bằng'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites_text',
            field=models.TextField(blank=True, null=True, verbose_name='Yêu cầu đầu vào (Text)'),
        ),
    ]
