# Generated by Django 5.2.8 on 2026-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userinterest_is_quizzed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Đáp án đánh giá', 'verbose_name_plural': '6.3. Đáp án đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Bộ đề đánh giá đầu vào', 'verbose_name_plural': '6.1. Bộ đề đánh giá đầu vào'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': 'Kết quả đánh giá', 'verbose_name_plural': '6.4. Kết quả đánh giá'},
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Độ khó (1-3)'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag năng lực'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Tư duy Lập trình & Cơ bản (Scratch/Basic)'), ('B', 'Phát triển Web Frontend (HTML/CSS/JS)'), ('C', 'Kỹ thuật Phần mềm & Hệ thống (Java/C#/.NET/SQL)'), ('D', 'Thuật toán & Công nghệ Cao (AI/Python/C++)')], max_length=1, null=True, verbose_name='Hạng mục đánh giá'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='test_category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
