# Generated by Django 5.2.8 on 2026-01-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_question_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatistic',
            fields=[
            ],
            options={
                'verbose_name': 'Thống kê tổng quan',
                'verbose_name_plural': 'Thống kê tổng quan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
