# Generated by Django 6.0 on 2026-01-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_quiz_choice_question_quiz_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='student',
        ),
        migrations.CreateModel(
            name='AIGeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bloom_levels', models.JSONField(default=list)),
                ('total_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz AI',
                'verbose_name_plural': 'Quiz được tạo bởi AI',
            },
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Câu hỏi')),
                ('bloom_level', models.CharField(max_length=50, verbose_name='Cấp độ Bloom')),
                ('explanation', models.TextField(blank=True, verbose_name='Giải thích')),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='courses.aigeneratedquiz')),
            ],
            options={
                'verbose_name': 'Câu hỏi AI',
                'verbose_name_plural': 'Câu hỏi AI',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_choices', to='courses.aiquestion')),
            ],
            options={
                'verbose_name': 'Lựa chọn AI',
                'verbose_name_plural': 'Lựa chọn AI',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
