# Generated by Django 6.0 on 2026-01-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_quiz_choice_question_quiz_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Chi tiết làm bài (JSON)'),
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('last_watched_position', models.IntegerField(default=0, verbose_name='Vị trí xem video (giây)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiến độ bài học',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
