# Generated by Django 5.2.8 on 2026-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Xem khóa học'), ('CLICK', 'Click vào chi tiết'), ('RATING', 'Đánh giá sao'), ('ENROLL', 'Đăng ký học')], default='VIEW', max_length=10)),
                ('rating', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tương tác người dùng',
                'verbose_name_plural': '5. Nhật ký tương tác (AI Data)',
            },
        ),
    ]
