# Generated by Django 5.2.8 on 2026-01-25 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('courses', '0006_coursestatistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('QUIZ', 'Kết quả làm bài'), ('ENROLL', 'Đăng ký học'), ('RATING', 'Đánh giá thủ công')], default='QUIZ', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'course', 'interaction_type')},
        ),
    ]
